language: node_js
services:
  - docker
node_js:
  - "stable"
cache:
  directories:
  - node_modules
env:
  - SERVICE_DIR=s_frontend
  - SERVICE_DIR=s_backend/s_b_core
script:
  - cd $SERVICE_DIR && npm install && npm run evaluate
  - docker build -t service . && docker run service /bin/bash -c "sleep 60 && shutdown -h now"
  