export const page: string;
export const container: string;
export const gridContainer: string;
export const gridRow: string;
export const gridElem: string;
export const listElem: string;
export const textLabel: string;
export const leftIconContainer: string;
export const rightIconContainer: string;
